name: Update Steam Stats

on:
    # Trigger on push events to the master branch
    # push:
    #     branches: [ master ]
    # for manual workflow trigger
    workflow_dispatch:
    schedule:
        # Runs every day at midnight IST (UTC+5:30)
        - cron: "30 18 * * *"

jobs:
  update-stats:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Steam stats
        run: python .github/scripts/fetch_steam_stats.py
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_WEB_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Steam Stats"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
