name: Steam Stats

on:
    workflow_dispatch:
    schedule:
        # Runs every Monday at 12 AM IST (UTC+5:30)
        - cron: "30 18 * * 0"

jobs:
    steam-stats:
        name: Steam Stats
        runs-on: ubuntu-latest
        steps:
          - name: GitHub App Token
            uses: actions/create-github-app-token@v1
            id: app-token
            with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.APP_PRIVATE_KEY }}

          - name: Steam Stats
            uses: nicconike/steam-stats@master
            env:
                GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
            with:
                STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
                STEAM_ID: ${{ vars.STEAM_ID }}
                STEAM_CUSTOM_ID: ${{ vars.STEAM_CUSTOM_ID }}
                WORKSHOP_STATS: True
                LOG_SCALE: True
