name: Readme

on:
    workflow_dispatch:
    schedule:
        # Runs every Monday at 5 AM IST (UTC+5:30)
        - cron: "30 23 * * 0"

jobs:
    update-readme:
        name: Dev Metrics
        runs-on: ubuntu-latest
        steps:
          - uses: anmol098/waka-readme-stats@master
            with:
                WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                SHOW_PROJECTS: "False"
                SHOW_COMMIT: "True"
                SHOW_LANGUAGE : "True"
                SHOW_TIMEZONE: "True"
                SHOW_EDITORS: "False"
                SHOW_LOC_CHART: "False"
                SHOW_PROFILE_VIEWS: "False"
                SHOW_SHORT_INFO: "False"
                SHOW_OS: "False"
                SHOW_LANGUAGE_PER_REPO: "False"
                SHOW_UPDATED_DATE: "True"
                SHOW_TOTAL_CODE_TIME: "True"
