name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # Runs everyday at midnight(IST)
    - cron: "30 18 * * *"

jobs:
  update-readme:
    name: DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
