name: Wakatime Leaderboards

on:
    schedule:
        # Runs every Monday at 12AM IST (UTC+5:30)
        - cron: "30 18 * * 0"
    workflow_dispatch:

jobs:
    update-readme:
        name: Wakatime Leaderboards
        runs-on: ubuntu-latest
        steps:
            - name: GitHub App Token
              uses: actions/create-github-app-token@v2
              id: app-token
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Wakatime Leaderboards
              uses: nicconike/wakatime-leaderboards@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
              env:
                  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
