name: Readme

on:
    # Trigger on push events to the master branch
    # push:
    #     branches: [ master ]
    # for manual workflow trigger
    workflow_dispatch:
    schedule:
        # Runs everyday at midnight IST (UTC+5:30)
        - cron: "30 18 * * 6"

jobs:
    update-readme:
        name: DevMetrics
        runs-on: ubuntu-latest
        steps:
          - uses: athul/waka-readme@master
            with:
                WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
                SHOW_TITLE: true
                SHOW_TOTAL: true
