name: Readme

on:
    # Trigger on push events to the master branch
    # push:
    #     branches: [ master ]
    # for manual workflow trigger
    workflow_dispatch:
    schedule:
        # Runs everyday at midnight IST (UTC+5:30)
        - cron: "30 18 * * *"

jobs:
    update-readme:
        name: DevMetrics
        runs-on: ubuntu-latest
        steps:
          - name: Profile Readme Development Stats
            uses: anmol098/waka-readme-stats@master
            with:
                WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
